const carrosEmDestaque = [
  {
    id: 1,
    nome: "Dodge Charger",
    preco: "R$ 450.000",
    imagem: "/dodge-charger-1970-preto.jpg",
    ano: "1970",
    combustivel: "Gasolina",
    assentos: "5 lugares",
  },
  {
    id: 2,
    nome: "Chevrolet Impala",
    preco: "R$ 280.000",
    imagem: "/chevrolet-impala-1967-vermelho.jpg",
    ano: "1967",
    combustivel: "Gasolina",
    assentos: "6 lugares",
  },
  {
    id: 3,
    nome: "Ford Mustang GT",
    preco: "R$ 320.000",
    imagem: "/ford-mustang-1968-verde.jpg",
    ano: "1968",
    combustivel: "Gasolina",
    assentos: "4 lugares",
  },
  {
    id: 4,
    nome: "Chevrolet Camaro Z/28",
    preco: "R$ 380.000",
    imagem: "/chevrolet-camaro-1969-vermelho.jpg",
    ano: "1969",
    combustivel: "Gasolina",
    assentos: "4 lugares",
  },
];